Assignment Pandas                                                                                
Group 5                                                                                                           
Sandeep Anumula                                                                                                        
Nikhil Bathini                                                                                     
SaiPrashanth Reddy Dyapa                                                                                          
Shirisha Teegala                                                                                           
Nikhith Vemula

1. Generate a Brief Statistical Summary:
Load the SP500.csv file into a Pandas DataFrame.
Generate and display a brief statistical summary of the data, 
including key metrics such as mean, median, and standard deviation.

In [18]:
import pandas as pd

# 1. Generate a brief statistical Summary
# Load File in to Pandas DataFrame.
df = pd.read_csv("SP500.csv")
# Getting mean median standard deviation of data
print(df.describe().loc[['mean','50%','std']])

            Open        High         Low       Close   Adj Close        Volume
mean  546.966024  550.229233  543.522697  547.091391  547.091391  8.945411e+08
50%   164.369995  165.050003  163.710007  164.289993  164.289993  8.794000e+07
std   643.238592  646.567762  639.645155  643.342927  643.342927  1.531001e+09

2. Sort Daily Gain/Loss for January 2018:
Filter the data to include only transactions from January 2018.
Sort the daily gain/loss values in descending order.
Save the sorted data to a new CSV file

In [19]:
# 2 . Sort Daily Gain or loss for 2018

# Reading the data from 2018 January month
jan_2018_month = df[df["Date"].astype(str).str[0:7] == "2018-01"]
gain_loss = jan_2018_month['Close'] - jan_2018_month['Open']

# Creating a data frame for gain or loss and sorting it
gain_loss_2018 = pd.DataFrame(gain_loss, columns=["Gain/Loss"])
gain_loss_2018.sort_values("Gain/Loss", axis=0, ascending=False, inplace=True)

# Display the sorted data
print(gain_loss_2018)

# Reading the sorted data to CSV
gain_loss_2018.to_csv("new.csv", index=False)

       Gain/Loss
17127  25.390137
17123  23.810059
17120  17.570069
17118  16.060058
17111  15.209961
17117  14.590088
17110  12.080079
17113  11.819824
17122   7.699951
17114   5.040039
17112   4.679931
17124   4.079834
17116   2.679931
17115   0.140137
17121  -4.369873
17126  -6.989990
17125  -7.879883
17130  -8.599853
17129 -10.310058
17128 -13.699951
17119 -22.540039

Find All Daily Gains of 2.5% and Above:
Identify and display all records where the daily gain is 2.5% or higher.

In [20]:
# 3. All daily gains of 2.5 and above

# Calculating gain loss per for daily data
gain_loss_per = ((df["Close"] - df["Open"])/df["Open"]) * 100

# Inserting gain loss per to the data frame

df.insert(3, 'gain_loss', df["Close"] - df["Open"])
df.insert(4, 'gain_loss_per', gain_loss_per)
print(df[ (df["gain_loss"] > 0) & (df["gain_loss_per"] >= 2.5)])

             Date         Open         High  gain_loss  gain_loss_per  \
3116   1962-05-29    55.500000    58.290001   2.580002       4.648652
3128   1962-06-15    54.330002    55.959999   1.559997       2.871336
3137   1962-06-28    52.980000    54.639999   1.430000       2.699132
3219   1962-10-24    53.490002    55.439999   1.719997       3.215549
4218   1966-10-12    74.910004    77.260002   2.129997       2.843408
...           ...          ...          ...        ...            ...
15579  2011-11-30  1196.719971  1247.109985  50.239990       4.198141
15593  2011-12-20  1205.719971  1242.819946  35.580078       2.950940
15851  2013-01-02  1426.189941  1462.430054  36.230103       2.540342
16518  2015-08-26  1872.750000  1943.089966  67.760010       3.618209
17134  2018-02-06  2614.780029  2701.040039  80.359864       3.073293

               Low        Close    Adj Close      Volume
3116     53.130001    58.080002    58.080002    14750000
3128     53.660000    55.889999    55.889999     7130000
3137     52.980000    54.410000    54.410000     5440000
3219     52.549999    55.209999    55.209999     6720000
4218     74.370003    77.040001    77.040001     6910000
...            ...          ...          ...         ...
15579  1196.719971  1246.959961  1246.959961  5801910000
15593  1205.719971  1241.300049  1241.300049  4055590000
15851  1426.189941  1462.420044  1462.420044  4202600000
16518  1872.750000  1940.510010  1940.510010  5338250000
17134  2593.070068  2695.139893  2695.139893  5891660000

[158 rows x 9 columns]

4. Identify Key Metrics:
Determine and display the highest daily gain and its corresponding date.
Determine and display the highest daily loss and its corresponding date.

In [21]:
# 4. Identify Key metrics
# Convert the columns to numeric data types
df['Open'] = pd.to_numeric(df['Open'], errors='coerce')
df['High'] = pd.to_numeric(df['High'], errors='coerce')
df['Low'] = pd.to_numeric(df['Low'], errors='coerce')

df['Daily Gain'] = df['High'] - df['Open']
df['Daily Loss'] = df['Open'] - df['Low']

highest_gain = df.loc[df['Daily Gain'].idxmax()]
highest_loss = df.loc[df['Daily Loss'].idxmax()]

print(f"The highest daily gain of {highest_gain['Daily Gain']:.2f} points occurred on {highest_gain['Date']}.")
print(f"The highest daily loss of {highest_loss['Daily Loss']:.2f} points occurred on {highest_loss['Date']}.")

The highest daily gain of 94.18 points occurred on 2008-10-13.
The highest daily loss of 104.45 points occurred on 2018-02-08.

Find and display the date with the highest daily transaction volume.

In [22]:
#THE MOST DAILY TRANSACTION VOLUME AND ITS DATE
# Convert 'Volume' to numeric
df['Volume'] = pd.to_numeric(df['Volume'], errors='coerce')

# Find the row with the highest volume and print the result
max_volume_row = df.loc[df['Volume'].idxmax()]
print(f" The date with the highest daily transaction volume is {max_volume_row['Date']} with the volume of {max_volume_row['Volume']}.")

 The date with the highest daily transaction volume is 2008-10-10 with the volume of 11456230000.


5. Segment and Analyze Volumes:
Segment the volumes into five bins using the following ranges:
1. O to 20% of the maximum volume
2. 20 to 40% of the maximum volume
3. 40 to 60% of the maximum volume
4. 60 to 80% of the maximum volume
5. 80 to 100% of the maximum volume
Add a new column named Volume bin cut to map each volume to its respective bin.
Segment the volumes into four quantiles and add a new column named Volume bin qeut 
to map each volume to its respective quantile.
Count the number of entries in each bin and each quantile.

Select and display rows where the volume falls into a specific bin.
Select and display rows where the volume falls into a specific quantile.
Sort the DataFrame based on the Volume bin cut column.
Sort the DataFrame based on the Volume bin qout column.

In [23]:
# Convert 'Volume' to numeric
df['Volume'] = pd.to_numeric(df['Volume'], errors='coerce')

# Maximum volume value
max_volume = df['Volume'].max()

# 1. Create bins based on volume percentages
bins = [0, 0.2 * max_volume, 0.4 * max_volume, 0.6 * max_volume, 0.8 * max_volume, max_volume]
labels = ['0-20%', '20-40%', '40-60%', '60-80%', '80-100%']
df['Volume bin cut'] = pd.cut(df['Volume'], bins=bins, labels=labels)

# 2. Segment volumes into four quantiles
df['Volume bin quantile'] = pd.qcut(df['Volume'], 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])

# 3. Count the number of entries in each bin and quantile
bin_counts = df['Volume bin cut'].value_counts()
quantile_counts = df['Volume bin quantile'].value_counts()

# Display bin counts
print("Bin Counts:")
print(bin_counts)

# Display quantile counts
print("\nQuantile Counts:")
print(quantile_counts)

# 4. Select rows in specific bins
bin_selected = df[df['Volume bin cut'] == '0-20%']
print(f"\nRows with Volume in '0-20%' bin:")
print(bin_selected)

# 5. Select rows in specific quantiles
quantile_selected = df[df['Volume bin quantile'] == 'Q1']
print(f"\nRows with Volume in 'Q1' quantile:")
print(quantile_selected)

# 6. Sort by volume bin cut
sorted_by_bin = df.sort_values(by='Volume bin cut')
print("\nData sorted by Volume bin cut:")
print(sorted_by_bin)

# 7. Sort by volume bin quantile
sorted_by_quantile = df.sort_values(by='Volume bin quantile')
print("\nData sorted by Volume bin quantile:")
print(sorted_by_quantile)

Bin Counts:
Volume bin cut
0-20%      14187
20-40%      2390
40-60%       540
60-80%        66
80-100%        8
Name: count, dtype: int64

Quantile Counts:
Volume bin quantile
Q1    4298
Q2    4298
Q4    4298
Q3    4297
Name: count, dtype: int64

Rows with Volume in '0-20%' bin:
             Date         Open         High  gain_loss  gain_loss_per  \
0      1950-01-03    16.660000    16.660000   0.000000       0.000000
1      1950-01-04    16.850000    16.850000   0.000000       0.000000
2      1950-01-05    16.930000    16.930000   0.000000       0.000000
3      1950-01-06    16.980000    16.980000   0.000000       0.000000
4      1950-01-09    17.080000    17.080000   0.000000       0.000000
...           ...          ...          ...        ...            ...
16984  2017-07-03  2431.389893  2439.169922  -2.379883      -0.097882
17085  2017-11-24  2600.419922  2604.209961   2.000000       0.076911
17106  2017-12-26  2679.090088  2682.739990   1.409912       0.052627
17107  2017-12-27  2682.100098  2685.639893   0.520019       0.019389
17108  2017-12-28  2686.100098  2687.659912   1.439941       0.053607

               Low        Close    Adj Close      Volume  Daily Gain  \
0        16.660000    16.660000    16.660000     1260000    0.000000
1        16.850000    16.850000    16.850000     1890000    0.000000
2        16.930000    16.930000    16.930000     2550000    0.000000
3        16.980000    16.980000    16.980000     2010000    0.000000
4        17.080000    17.080000    17.080000     2520000    0.000000
...            ...          ...          ...         ...         ...
16984  2428.689941  2429.010010  2429.010010  1962290000    7.780029
17085  2600.419922  2602.419922  2602.419922  1349780000    3.790039
17106  2677.959961  2680.500000  2680.500000  1968780000    3.649902
17107  2678.909912  2682.620117  2682.620117  2202080000    3.539795
17108  2682.689941  2687.540039  2687.540039  2153330000    1.559814

       Daily Loss Volume bin cut Volume bin quantile
0        0.000000          0-20%                  Q1
1        0.000000          0-20%                  Q1
2        0.000000          0-20%                  Q1
3        0.000000          0-20%                  Q1
4        0.000000          0-20%                  Q1
...           ...            ...                 ...
16984    2.699952          0-20%                  Q4
17085    0.000000          0-20%                  Q4
17106    1.130127          0-20%                  Q4
17107    3.190186          0-20%                  Q4
17108    3.410157          0-20%                  Q4

[14187 rows x 13 columns]

Rows with Volume in 'Q1' quantile:
            Date       Open       High  gain_loss  gain_loss_per        Low  \
0     1950-01-03  16.660000  16.660000   0.000000       0.000000  16.660000
1     1950-01-04  16.850000  16.850000   0.000000       0.000000  16.850000
2     1950-01-05  16.930000  16.930000   0.000000       0.000000  16.930000
3     1950-01-06  16.980000  16.980000   0.000000       0.000000  16.980000
4     1950-01-09  17.080000  17.080000   0.000000       0.000000  17.080000
...          ...        ...        ...        ...            ...        ...
6138  1974-07-05  84.250000  84.449997  -0.589996      -0.700292  83.169998
6164  1974-08-12  80.860001  81.260002  -1.110001      -1.372744  79.300003
6241  1974-11-29  69.940002  70.489998   0.029999       0.042892  69.180000
6440  1975-09-15  83.300003  83.489998  -0.420006      -0.504209  82.290001
7034  1978-01-20  90.089996  90.269997  -0.199997      -0.221997  89.410004

          Close  Adj Close   Volume  Daily Gain  Daily Loss Volume bin cut  \
0     16.660000  16.660000  1260000    0.000000    0.000000          0-20%
1     16.850000  16.850000  1890000    0.000000    0.000000          0-20%
2     16.930000  16.930000  2550000    0.000000    0.000000          0-20%
3     16.980000  16.980000  2010000    0.000000    0.000000          0-20%
4     17.080000  17.080000  2520000    0.000000    0.000000          0-20%
...         ...        ...      ...         ...         ...            ...
6138  83.660004  83.660004  7400000    0.199997    1.080002          0-20%
6164  79.750000  79.750000  7780000    0.400001    1.559998          0-20%
6241  69.970001  69.970001  7400000    0.549996    0.760002          0-20%
6440  82.879997  82.879997  8670000    0.189995    1.010002          0-20%
7034  89.889999  89.889999  7580000    0.180001    0.679992          0-20%

     Volume bin quantile
0                     Q1
1                     Q1
2                     Q1
3                     Q1
4                     Q1
...                  ...
6138                  Q1
6164                  Q1
6241                  Q1
6440                  Q1
7034                  Q1

[4298 rows x 13 columns]

Data sorted by Volume bin cut:
             Date         Open         High  gain_loss  gain_loss_per  \
0      1950-01-03    16.660000    16.660000   0.000000       0.000000
9453   1987-08-17   333.980011   335.429993   0.129974       0.038917
9454   1987-08-18   334.100006   334.109985  -4.850006      -1.451663
9455   1987-08-19   329.260010   329.890015   0.569977       0.173108
9456   1987-08-20   331.489990   335.190002   3.350006       1.010590
...           ...          ...          ...        ...            ...
14818  2008-11-21   755.840027   801.200012  44.190002       5.846476
14773  2008-09-19  1213.109985  1265.119995  41.969971       3.459700
15183  2010-05-07  1127.040039  1135.130005 -16.160034      -1.433847
15182  2010-05-06  1164.380005  1167.579956 -36.229981      -3.111526
14770  2008-09-16  1188.310059  1214.839966  25.289917       2.128225

               Low        Close    Adj Close       Volume  Daily Gain  \
0        16.660000    16.660000    16.660000      1260000    0.000000
9453    332.880005   334.109985   334.109985    166100000    1.449982
9454    326.429993   329.250000   329.250000    198400000    0.009979
9455    326.540009   329.829987   329.829987    180900000    0.630005
9456    329.829987   334.839996   334.839996    196600000    3.700012
...            ...          ...          ...          ...         ...
14818   741.020020   800.030029   800.030029   9495900000   45.359985
14773  1213.109985  1255.079956  1255.079956   9387170000   52.010010
15183  1094.150024  1110.880005  1110.880005   9472910000    8.089966
15182  1065.790039  1128.150024  1128.150024  10617810000    3.199951
14770  1169.280029  1213.599976  1213.599976   9459830000   26.529907

       Daily Loss Volume bin cut Volume bin quantile
0        0.000000          0-20%                  Q1
9453     1.100006          0-20%                  Q3
9454     7.670013          0-20%                  Q3
9455     2.720001          0-20%                  Q3
9456     1.660003          0-20%                  Q3
...           ...            ...                 ...
14818   14.820007        80-100%                  Q4
14773    0.000000        80-100%                  Q4
15183   32.890015        80-100%                  Q4
15182   98.589966        80-100%                  Q4
14770   19.030030        80-100%                  Q4

[17191 rows x 13 columns]

Data sorted by Volume bin quantile:
             Date         Open         High  gain_loss  gain_loss_per  \
0      1950-01-03    16.660000    16.660000   0.000000       0.000000
2858   1961-05-18    66.989998    66.989998   0.000000       0.000000
2859   1961-05-19    67.269997    67.269997   0.000000       0.000000
2860   1961-05-22    66.849998    66.849998   0.000000       0.000000
2861   1961-05-23    66.680000    66.680000   0.000000       0.000000
...           ...          ...          ...        ...            ...
14330  2006-12-14  1413.160034  1427.229980  12.329956       0.872510
14331  2006-12-15  1425.479980  1431.630005   1.609986       0.112943
14332  2006-12-18  1427.079956  1431.810059  -4.599976      -0.322335
14318  2006-11-28  1381.609985  1387.910034   5.109986       0.369857
17190  2018-04-27  2675.469971  2677.350098  -5.560059      -0.207816

               Low        Close    Adj Close      Volume  Daily Gain  \
0        16.660000    16.660000    16.660000     1260000    0.000000
2858     66.989998    66.989998    66.989998     4610000    0.000000
2859     67.269997    67.269997    67.269997     4200000    0.000000
2860     66.849998    66.849998    66.849998     4070000    0.000000
2861     66.680000    66.680000    66.680000     3660000    0.000000
...            ...          ...          ...         ...         ...
14330  1413.160034  1425.489990  1425.489990  2729700000   14.069946
14331  1425.479980  1427.089966  1427.089966  3229580000    6.150025
14332  1420.650024  1422.479980  1422.479980  2568140000    4.730103
14318  1377.829956  1386.719971  1386.719971  2639750000    6.300049
17190  2659.010010  2669.909912  2669.909912  3219030000    1.880127

       Daily Loss Volume bin cut Volume bin quantile
0        0.000000          0-20%                  Q1
2858     0.000000          0-20%                  Q1
2859     0.000000          0-20%                  Q1
2860     0.000000          0-20%                  Q1
2861     0.000000          0-20%                  Q1
...           ...            ...                 ...
14330    0.000000         20-40%                  Q4
14331    0.000000         20-40%                  Q4
14332    6.429932         20-40%                  Q4
14318    3.780029         20-40%                  Q4
17190   16.459961         20-40%                  Q4

[17191 rows x 13 columns]

1. Monthly Report for 2017-2018:
Generate a report showing the monthly average of the open price, close price, transaction volume, and gain/loss.
Perform a query to find all months where the open price falls within a specified range.

In [24]:
# Monthly Report for 2017 - 2018

# Filter valid dates and convert types
df = df[df['Date'].str.match(r'\d{4}-\d{2}-\d{2}')]
df[['Open', 'Close', 'Volume']] = df[['Open', 'Close', 'Volume']].apply(pd.to_numeric, errors='coerce')

# Convert 'Date' to datetime and extract YearMonth
df['Date'] = pd.to_datetime(df['Date'])
df['YearMonth'] = df['Date'].dt.to_period('M')

# Filter data for 2017-2018
df_filtered = df[(df['Date'].between('2017-01-01', '2018-12-31'))]

# Generate monthly report
monthly_report = df_filtered.groupby('YearMonth').agg(
    MonthlyAvgOpen=('Open', 'mean'),
    MonthlyAvgClose=('Close', 'mean'),
    MonthlyTotalVolume=('Volume', 'sum'),
    GainLoss=('Close', 'last')
)

# Subtract first open price to calculate GainLoss
monthly_report['GainLoss'] -= df_filtered.groupby('YearMonth')['Open'].first()

# Filter months where open price is between 2500 and 2600
months_in_range = df_filtered.loc[df_filtered['Open'].between(2500, 2600), 'YearMonth'].unique()

# Print results
print("Monthly Report for 2017-2018:")
print(monthly_report)

print("\nMonths with Open Price between 2500 and 2600:")
print(months_in_range)

Monthly Report for 2017-2018:
           MonthlyAvgOpen  MonthlyAvgClose  MonthlyTotalVolume    GainLoss
YearMonth
2017-01       2273.531970      2275.115979         70483180000   27.300049
2017-02       2325.585282      2329.910542         69162420000   78.049805
2017-03       2366.868705      2366.822170         81547770000  -17.409912
2017-04       2360.150005      2359.309455         65265670000   21.859863
2017-05       2394.470004      2395.345881         79607170000   23.300049
2017-06       2434.683605      2433.985451         81002490000    7.760010
2017-07       2453.039490      2454.102502         63169400000   38.910156
2017-08       2456.749968      2456.223070         70616030000   -5.450196
2017-09       2491.332495      2492.841040         66337980000   44.940185
2017-10       2555.807273      2556.997270         70871570000   54.060059
2017-11       2590.306164      2593.605736         73173260000   64.370117
2017-12       2666.069995      2664.340527         65251190000   28.510009
2018-01       2785.686651      2789.803816         76860120000  140.080079
2018-02       2710.269467      2705.155248         79579410000 -102.619873
2018-03       2707.860003      2702.773821         76349800000  -74.349854
2018-04       2656.397986      2653.903967         65914060000   36.459961

Months with Open Price between 2500 and 2600:
<PeriodArray>
['2017-09', '2017-10', '2017-11', '2018-04']
Length: 4, dtype: period[M]

2. Yearly Report from 1950 to 2018:
Create a report with the annual average of the open price, close price, transaction volume, and gain/loss for 
each year from 1950 to 2018.
Identify the most profitable year.

In [25]:
#ANNUAL AVERAGE YEARLY REPORT FOR 1950 TO 2018.

# Convert 'Date' to string before applying .str functions (Fixes the error)
df = df[df['Date'].astype(str).str.match(r'\d{4}-\d{2}-\d{2}')]

# Convert necessary columns to numeric
df[['Open', 'Close', 'Volume']] = df[['Open', 'Close', 'Volume']].apply(pd.to_numeric, errors='coerce')

# Convert 'Date' column to datetime and extract Year
df['Date'] = pd.to_datetime(df['Date'])
df['Year'] = df['Date'].dt.year

# Filter data for years 1950-2018
df_filtered = df[df['Year'].between(1950, 2018)]

# Generate yearly report
yearly_report = df_filtered.groupby('Year').agg(
    AnnualAvgOpen=('Open', 'mean'),
    AnnualAvgClose=('Close', 'mean'),
    AnnualTotalVolume=('Volume', 'sum')
)

# Compute GainLoss directly
yearly_report['GainLoss'] = df_filtered.groupby('Year')['Close'].last() - df_filtered.groupby('Year')['Open'].first()

# Find the most profitable year
most_profitable_year = yearly_report.loc[yearly_report['GainLoss'].idxmax()]

# Print results
print("Yearly Report from 1950 to 2018:")
print(yearly_report)

print("\nMost Profitable Year:")
print(most_profitable_year)

Yearly Report from 1950 to 2018:
      AnnualAvgOpen  AnnualAvgClose  AnnualTotalVolume    GainLoss
Year
1950      18.397269       18.397269          500300000    3.770000
1951      22.321888       22.321888          427680000    3.000000
1952      24.496160       24.496160          327040000    2.770001
1953      24.722590       24.722590          354700000   -1.730002
1954      29.724087       29.724087          571980000   11.029999
...             ...             ...                ...         ...
2014    1930.754485     1931.376110       845405230000  213.039917
2015    2061.268016     2061.067741       921218600000  -14.959961
2016    2094.091550     2094.651264       984118470000  200.630127
2017    2448.275888     2449.076379       856488130000  422.040039
2018    2715.895794     2713.829129       298703390000  -13.820068

[69 rows x 4 columns]

Most Profitable Year:
AnnualAvgOpen        1.642299e+03
AnnualAvgClose       1.643799e+03
AnnualTotalVolume    8.464596e+11
GainLoss             4.221700e+02
Name: 2013, dtype: float64

3. Every Five-Year Report from 1950 to 2018
Generate a report showing the average open price, close price, transaction volume, 
and gain/loss for every five-year period from 1950 to 2018.
Determine the most profitable five-year period.

In [26]:
#EVERY FIVE YEAR AVERAGE REPORT
# Filter valid dates
df = df[df['Date'].astype(str).str.match(r'\d{4}-\d{2}-\d{2}')]

# Convert necessary columns to numeric
df[['Open', 'Close', 'Volume']] = df[['Open', 'Close', 'Volume']].apply(pd.to_numeric, errors='coerce')

# Convert 'Date' to datetime and extract Year
df['Date'] = pd.to_datetime(df['Date'])
df['Year'] = df['Date'].dt.year

# Filter data for the years 1950-2018
df_filtered = df[df['Year'].between(1950, 2018)]

# Create five-year groupings
df_filtered['FiveYearGroup'] = ((df_filtered['Year'] - 1950) // 5) * 5 + 1950

# Generate five-year report
five_year_report = df_filtered.groupby('FiveYearGroup').agg(
    FiveYearAvgOpen=('Open', 'mean'),
    FiveYearAvgClose=('Close', 'mean'),
    FiveYearTotalVolume=('Volume', 'sum')
)

# Compute GainLoss directly
five_year_report['GainLoss'] = df_filtered.groupby('FiveYearGroup')['Close'].last() - df_filtered.groupby('FiveYearGroup')['Open'].first()

# Find the most profitable five-year period
most_profitable_five_year = five_year_report.loc[five_year_report['GainLoss'].idxmax()]

# Print results
print("Every Five-Year Report from 1950 to 2018:")
print(five_year_report)

print("\nMost Profitable Five-Year Period:")
print(most_profitable_five_year)

Every Five-Year Report from 1950 to 2018:
               FiveYearAvgOpen  FiveYearAvgClose  FiveYearTotalVolume  \
FiveYearGroup
1950                 23.948002         23.948002           2181700000
1955                 47.045230         47.045230           3329710000
1960                 67.134913         67.143545           5132620000
1965                 92.144817         92.151681          11759150000
1970                 96.146398         96.124893          18554220000
1975                 97.070111         97.102209          30696980000
1980                137.429652        137.478087          84324810000
1985                259.686461        259.837395         193531620000
1990                407.601012        407.684031         276756510000
1995                898.511394        899.311165         697845170000
2000               1142.276792       1142.076967        1633887690000
2005               1232.307609       1232.326600        4572779030000
2010               1471.892304       1472.574681        4786747760000
2015               2250.783993       2250.932440        3060528590000

                  GainLoss
FiveYearGroup
1950             19.320000
1955             23.139999
1960             24.840000
1965              7.309998
1970            -23.500000
1975             39.290000
1980             59.300003
1985            186.199997
1990            105.869995
1995           1010.040009
2000           -257.329956
2005            -96.820068
2010            942.339843
2015            611.010010

Most Profitable Five-Year Period:
FiveYearAvgOpen        8.985114e+02
FiveYearAvgClose       8.993112e+02
FiveYearTotalVolume    6.978452e+11
GainLoss               1.010040e+03
Name: 1995, dtype: float64

Analyzing Sacramentorealestatetransactions.csv Using Pandas
using Pandas operations and answer the following questions:
4. Regroup the Data:
Regroup the data first by city name, and then by property type.
5. Transaction Statistics.
* For each city and each property type, find the highest, median, and lowest transac-tion amounts.
6. Average Transactions by Zipcode and Type:
* For each zipcode and each property type, calculate the average transaction amount.

In [27]:
dataframe=pd.read_csv("Sacramentorealestatetransactions.csv")
# Grouping the data first by city name and then by type
grouped_data = dataframe.groupby(['city', 'type']).agg(
    AveragePrice=('price', 'mean'),
    TotalTransactions=('price', 'count')
).reset_index()
print(grouped_data)

               city          type   AveragePrice  TotalTransactions
0          ANTELOPE         Condo  115000.000000                  1
1          ANTELOPE   Residential  236168.156250                 32
2            AUBURN         Condo  260000.000000                  1
3            AUBURN  Multi-Family  285000.000000                  1
4            AUBURN   Residential  494818.000000                  3
5      CAMERON PARK         Condo  119000.000000                  1
6      CAMERON PARK   Residential  286562.500000                  8
7        CARMICHAEL         Condo  190544.666667                  3
8        CARMICHAEL   Residential  314238.882353                 17
9    CITRUS HEIGHTS         Condo   92625.000000                  2
10   CITRUS HEIGHTS  Multi-Family  256054.000000                  1
11   CITRUS HEIGHTS   Residential  190866.187500                 32
12             COOL   Residential  300000.000000                  1
13  DIAMOND SPRINGS   Residential  216033.000000                  1
14        EL DORADO   Residential  247000.000000                  2
15  EL DORADO HILLS   Residential  491698.956522                 23
16        ELK GROVE         Condo  114666.666667                  6
17        ELK GROVE   Residential  279851.638889                108
18          ELVERTA   Residential  132866.000000                  4
19        FAIR OAKS         Condo  142500.000000                  1
20        FAIR OAKS   Residential  323625.750000                  8
21           FOLSOM         Condo  240000.000000                  1
22           FOLSOM   Residential  425895.187500                 16
23       FORESTHILL   Residential  194818.000000                  1
24             GALT   Residential  236943.428571                 21
25    GARDEN VALLEY   Residential  490000.000000                  1
26       GOLD RIVER         Condo  300000.000000                  1
27       GOLD RIVER   Residential  377333.333333                  3
28      GRANITE BAY   Residential  678733.333333                  3
29        GREENWOOD   Residential  395000.000000                  1
30          LINCOLN         Condo  163000.000000                  2
31          LINCOLN   Residential   94640.385714                 70
32           LOOMIS   Residential  567000.000000                  2
33           MATHER   Residential  237800.000000                  1
34     MEADOW VISTA   Residential  230000.000000                  1
35  NORTH HIGHLANDS   Residential  135659.333333                 21
36       ORANGEVALE   Residential  279159.545455                 11
37           PENRYN   Residential  506688.000000                  1
38      PLACERVILLE   Residential  363863.400000                 10
39    POLLOCK PINES   Residential  240302.666667                  3
40   RANCHO CORDOVA         Condo   94905.000000                  1
41   RANCHO CORDOVA  Multi-Family  236000.000000                  1
42   RANCHO CORDOVA   Residential  270940.807692                 26
43   RANCHO MURIETA   Residential  297750.000000                  3
44        RIO LINDA   Residential  172727.615385                 13
45          ROCKLIN   Residential  381835.823529                 17
46        ROSEVILLE         Condo  192071.428571                  7
47        ROSEVILLE   Residential  347142.829268                 41
48       SACRAMENTO         Condo  137690.703704                 27
49       SACRAMENTO  Multi-Family  214189.700000                 10
50       SACRAMENTO   Residential  201359.584577                402
51  SHINGLE SPRINGS        Unkown  275000.000000                  1
52      SLOUGHHOUSE   Residential    2000.000000                  1
53     WALNUT GROVE   Residential  380000.000000                  1
54  WEST SACRAMENTO   Residential  170700.000000                  3
55           WILTON   Residential  617508.400000                  5

In [28]:
# Grouping the data by city and type and calculating the highest, median, and lowest transactions
grouped_data = dataframe.groupby(['city', 'type'])['price'].agg(
    HighestTransaction='max',
    MedianTransaction='median',
    LowestTransaction='min'
).reset_index()
print(grouped_data)

               city          type  HighestTransaction  MedianTransaction  \
0          ANTELOPE         Condo              115000           115000.0
1          ANTELOPE   Residential              408431           232600.0
2            AUBURN         Condo              260000           260000.0
3            AUBURN  Multi-Family              285000           285000.0
4            AUBURN   Residential              560000           504000.0
5      CAMERON PARK         Condo              119000           119000.0
6      CAMERON PARK   Residential              425000           219750.0
7        CARMICHAEL         Condo              250134           182000.0
8        CARMICHAEL   Residential              668365           266000.0
9    CITRUS HEIGHTS         Condo              116250            92625.0
10   CITRUS HEIGHTS  Multi-Family              256054           256054.0
11   CITRUS HEIGHTS   Residential              305000           191268.0
12             COOL   Residential              300000           300000.0
13  DIAMOND SPRINGS   Residential              216033           216033.0
14        EL DORADO   Residential              289000           247000.0
15  EL DORADO HILLS   Residential              879000           471000.0
16        ELK GROVE         Condo              145000           116500.0
17        ELK GROVE   Residential              510000           258000.0
18          ELVERTA   Residential              140000           132732.0
19        FAIR OAKS         Condo              142500           142500.0
20        FAIR OAKS   Residential              680000           258006.5
21           FOLSOM         Condo              240000           240000.0
22           FOLSOM   Residential              636000           443500.0
23       FORESTHILL   Residential              194818           194818.0
24             GALT   Residential              420000           220000.0
25    GARDEN VALLEY   Residential              490000           490000.0
26       GOLD RIVER         Condo              300000           300000.0
27       GOLD RIVER   Residential              528000           305000.0
28      GRANITE BAY   Residential              760000           676200.0
29        GREENWOOD   Residential              395000           395000.0
30          LINCOLN         Condo              188000           163000.0
31          LINCOLN   Residential              512000             4897.0
32           LOOMIS   Residential              839000           567000.0
33           MATHER   Residential              237800           237800.0
34     MEADOW VISTA   Residential              230000           230000.0
35  NORTH HIGHLANDS   Residential              224252           129000.0
36       ORANGEVALE   Residential              475000           252155.0
37           PENRYN   Residential              506688           506688.0
38      PLACERVILLE   Residential              677048           325000.0
39    POLLOCK PINES   Residential              280908           265000.0
40   RANCHO CORDOVA         Condo               94905            94905.0
41   RANCHO CORDOVA  Multi-Family              236000           236000.0
42   RANCHO CORDOVA   Residential              430000           281028.0
43   RANCHO MURIETA   Residential              425000           370500.0
44        RIO LINDA   Residential              300000           164000.0
45          ROCKLIN   Residential              600000           370000.0
46        ROSEVILLE         Condo              350000           170000.0
47        ROSEVILLE   Residential              614000           326951.0
48       SACRAMENTO         Condo              360000           110700.0
49       SACRAMENTO  Multi-Family              416767           187290.0
50       SACRAMENTO   Residential              699000           180000.0
51  SHINGLE SPRINGS        Unkown              275000           275000.0
52      SLOUGHHOUSE   Residential                2000             2000.0
53     WALNUT GROVE   Residential              380000           380000.0
54  WEST SACRAMENTO   Residential              200100           165000.0
55           WILTON   Residential              884790           579093.0

    LowestTransaction
0              115000
1              126640
2              260000
3              285000
4              420454
5              119000
6              195000
7              139500
8              181872
9               69000
10             256054
11              30000
12             300000
13             216033
14             205000
15             235738
16              71000
17             152000
18             126000
19             142500
20             185000
21             240000
22             200000
23             194818
24             106716
25             490000
26             300000
27             299000
28             600000
29             395000
30             138000
31               1551
32             295000
33             237800
34             230000
35              63000
36             183200
37             506688
38             205000
39             175000
40              94905
41             236000
42             115000
43              97750
44              30000
45             230095
46             115000
47             160000
48              40000
49             100000
50              55422
51             275000
52               2000
53             380000
54             147000
55             372000

In [29]:
# Grouping the data by zipcode and type and calculating the average transactions
grouped_data = dataframe.groupby(['zip', 'type'])['price'].mean().reset_index()
print(grouped_data)

       zip          type          price
0    95603         Condo  260000.000000
1    95603  Multi-Family  285000.000000
2    95603   Residential  494818.000000
3    95608         Condo  190544.666667
4    95608   Residential  314238.882353
..     ...           ...            ...
96   95842  Multi-Family  179580.000000
97   95842   Residential  157920.812500
98   95843         Condo  115000.000000
99   95843   Residential  236168.156250
100  95864   Residential  364400.000000

[101 rows x 3 columns]